export const AGREGA_PRODUCTO = 'AGREGA_PRODUCTO';
export const AGREGA_PRODUCTO_EXITO = 'AGREGA_PRODUCTO_EXITO';
export const AGREGA_PRODUCTO_ERROR = 'AGREGA_PRODUCTO_ERROR';

export const COMENZAR_DESCARGA_PRODUCTOS = 'COMENZAR_DESCARGA_PRODUCTOS';
export const DESCARGA_PRODUCTOS_EXITO = 'DESCARGA_PRODUCTOS_EXITO';
export const DESCARGA_PRODUCTOS_ERROR = 'DESCARGA_PRODUCTOS_ERROR';

export const GET_PRODUCTO_ELIMINAR = 'GET_PRODUCTO_ELIMINAR';
export const PRODUCTO_ELIMINAR_EXITO = 'PRODUCTO_ELIMINAR_EXITO';
export const PRODUCTO_ELIMINAR_ERROR = 'PRODUCTO_ELIMINAR_ERROR';